using UnityEngine;

namespace GoodLuckValley.Gameplay.Player.Motor
{
    /// <summary>
    /// Represents the output generated by the motor, primarily indicating the
    /// velocity of the player or object in a 2D space.
    /// </summary>
    public readonly struct MotorOutput
    {
        public readonly Vector2 Velocity;

        public MotorOutput(Vector2 velocity) => Velocity = velocity;
    }
}