//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GoodLuckValley.Player.Input
{
    public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player Controls"",
            ""id"": ""543a31e8-eb91-4c8d-8588-89f60c758abf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""63b03301-cc2e-41df-a0d4-9ec27f2bbd31"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e5e58356-e002-46ad-b80b-c81069583ac9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""e1b9c303-7756-4b03-85a0-a0f04456c62c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fast Fall"",
                    ""type"": ""Button"",
                    ""id"": ""84465b74-0a9b-411f-961e-8edc2e21d84c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recall Last"",
                    ""type"": ""Button"",
                    ""id"": ""c85732e6-7477-41a0-9618-26ccad311f76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recall All"",
                    ""type"": ""Button"",
                    ""id"": ""5e93ad46-46fa-43c7-89b7-60bbddead246"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick Bounce"",
                    ""type"": ""Button"",
                    ""id"": ""e2d36caa-923d-48ce-af0f-868f7522b618"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""99ca68e2-a76d-4c30-af35-95e3b4c7cc60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c6e9ca60-234a-4187-b343-4b22b5490504"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DevTools"",
                    ""type"": ""Button"",
                    ""id"": ""070e5ce1-f82c-4de5-80e2-7e578ec94f80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NoClip"",
                    ""type"": ""Button"",
                    ""id"": ""3e1d270d-77a0-4262-8ebb-b4e50712d23a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnlockPowers"",
                    ""type"": ""Button"",
                    ""id"": ""508263da-505f-4a9b-afe7-d973db585170"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""c3f0d9c5-225f-4d94-bc53-18caf4e85b7c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fast Slide"",
                    ""type"": ""Button"",
                    ""id"": ""f3278430-da7d-4b5b-8069-7e25869ef67f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crawl"",
                    ""type"": ""Button"",
                    ""id"": ""df3ba777-cea6-4518-ab29-8dd2a2b1686a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""233514ea-d20f-4404-9c05-07fc034bc200"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f6be2d4a-fbce-4c41-9548-6a6bd748f9a3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b691705d-91bb-4e82-8730-947a2fec27d0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""93a4c792-7170-4831-8523-07b0ceb14b4b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""58c1e54b-f2c4-4bc4-aad6-68d1c4328bc8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c183320a-8142-4dd2-a66f-dae15516ff97"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6498082-3166-44bd-ac23-41f937f5d4fb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1126bba6-5748-4d28-9203-41e05ff9edd9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fast Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ced0ef36-460c-403b-9a50-9b72a4d09224"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recall Last"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2908c3af-432c-4958-9cac-9421077c1201"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recall All"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""692d18a4-249c-414e-9075-8dcbfeb3014b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick Bounce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fdd9cd8-53e7-479c-9610-723009927be1"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ca8baf3-5c02-46fa-b7d4-84e26469e985"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6034c311-c93f-42d2-b751-db7b0b73c0be"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6309d0a2-0cbb-4538-a5a5-e9071820f104"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e586aa42-9b3b-4b01-a59c-09b35ed184cc"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnlockPowers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""eea2cb55-5bb9-49ba-9a57-0980bbecc359"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6fb79e01-6b2a-4ea4-8a0b-9de7c38b3cbf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""373d69d1-f1b3-4e8d-9e5a-7a25dacab165"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a2cfcfb2-9552-4b25-9bd8-b91dec178d2a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fast Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35f1f484-f3cb-48c0-bfb0-deb9fdc12b62"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crawl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""0394a4c8-4f01-462f-8a02-73d8422b661b"",
            ""actions"": [
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""1edcc436-aaa1-4983-82ac-86d33e72e941"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3cd5549d-15e5-4fd0-aabf-b547ce88fc0b"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b92129ab-a493-442f-88a6-0471583894b0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65548503-24a4-4e23-8609-a5165aef51e0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Player Controls
            m_PlayerControls = asset.FindActionMap("Player Controls", throwIfNotFound: true);
            m_PlayerControls_Move = m_PlayerControls.FindAction("Move", throwIfNotFound: true);
            m_PlayerControls_Jump = m_PlayerControls.FindAction("Jump", throwIfNotFound: true);
            m_PlayerControls_Throw = m_PlayerControls.FindAction("Throw", throwIfNotFound: true);
            m_PlayerControls_FastFall = m_PlayerControls.FindAction("Fast Fall", throwIfNotFound: true);
            m_PlayerControls_RecallLast = m_PlayerControls.FindAction("Recall Last", throwIfNotFound: true);
            m_PlayerControls_RecallAll = m_PlayerControls.FindAction("Recall All", throwIfNotFound: true);
            m_PlayerControls_QuickBounce = m_PlayerControls.FindAction("Quick Bounce", throwIfNotFound: true);
            m_PlayerControls_Interact = m_PlayerControls.FindAction("Interact", throwIfNotFound: true);
            m_PlayerControls_Pause = m_PlayerControls.FindAction("Pause", throwIfNotFound: true);
            m_PlayerControls_DevTools = m_PlayerControls.FindAction("DevTools", throwIfNotFound: true);
            m_PlayerControls_NoClip = m_PlayerControls.FindAction("NoClip", throwIfNotFound: true);
            m_PlayerControls_UnlockPowers = m_PlayerControls.FindAction("UnlockPowers", throwIfNotFound: true);
            m_PlayerControls_Look = m_PlayerControls.FindAction("Look", throwIfNotFound: true);
            m_PlayerControls_FastSlide = m_PlayerControls.FindAction("Fast Slide", throwIfNotFound: true);
            m_PlayerControls_Crawl = m_PlayerControls.FindAction("Crawl", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Start = m_UI.FindAction("Start", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player Controls
        private readonly InputActionMap m_PlayerControls;
        private List<IPlayerControlsActions> m_PlayerControlsActionsCallbackInterfaces = new List<IPlayerControlsActions>();
        private readonly InputAction m_PlayerControls_Move;
        private readonly InputAction m_PlayerControls_Jump;
        private readonly InputAction m_PlayerControls_Throw;
        private readonly InputAction m_PlayerControls_FastFall;
        private readonly InputAction m_PlayerControls_RecallLast;
        private readonly InputAction m_PlayerControls_RecallAll;
        private readonly InputAction m_PlayerControls_QuickBounce;
        private readonly InputAction m_PlayerControls_Interact;
        private readonly InputAction m_PlayerControls_Pause;
        private readonly InputAction m_PlayerControls_DevTools;
        private readonly InputAction m_PlayerControls_NoClip;
        private readonly InputAction m_PlayerControls_UnlockPowers;
        private readonly InputAction m_PlayerControls_Look;
        private readonly InputAction m_PlayerControls_FastSlide;
        private readonly InputAction m_PlayerControls_Crawl;
        public struct PlayerControlsActions
        {
            private @PlayerInputActions m_Wrapper;
            public PlayerControlsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_PlayerControls_Move;
            public InputAction @Jump => m_Wrapper.m_PlayerControls_Jump;
            public InputAction @Throw => m_Wrapper.m_PlayerControls_Throw;
            public InputAction @FastFall => m_Wrapper.m_PlayerControls_FastFall;
            public InputAction @RecallLast => m_Wrapper.m_PlayerControls_RecallLast;
            public InputAction @RecallAll => m_Wrapper.m_PlayerControls_RecallAll;
            public InputAction @QuickBounce => m_Wrapper.m_PlayerControls_QuickBounce;
            public InputAction @Interact => m_Wrapper.m_PlayerControls_Interact;
            public InputAction @Pause => m_Wrapper.m_PlayerControls_Pause;
            public InputAction @DevTools => m_Wrapper.m_PlayerControls_DevTools;
            public InputAction @NoClip => m_Wrapper.m_PlayerControls_NoClip;
            public InputAction @UnlockPowers => m_Wrapper.m_PlayerControls_UnlockPowers;
            public InputAction @Look => m_Wrapper.m_PlayerControls_Look;
            public InputAction @FastSlide => m_Wrapper.m_PlayerControls_FastSlide;
            public InputAction @Crawl => m_Wrapper.m_PlayerControls_Crawl;
            public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerControlsActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Throw.started += instance.OnThrow;
                @Throw.performed += instance.OnThrow;
                @Throw.canceled += instance.OnThrow;
                @FastFall.started += instance.OnFastFall;
                @FastFall.performed += instance.OnFastFall;
                @FastFall.canceled += instance.OnFastFall;
                @RecallLast.started += instance.OnRecallLast;
                @RecallLast.performed += instance.OnRecallLast;
                @RecallLast.canceled += instance.OnRecallLast;
                @RecallAll.started += instance.OnRecallAll;
                @RecallAll.performed += instance.OnRecallAll;
                @RecallAll.canceled += instance.OnRecallAll;
                @QuickBounce.started += instance.OnQuickBounce;
                @QuickBounce.performed += instance.OnQuickBounce;
                @QuickBounce.canceled += instance.OnQuickBounce;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @DevTools.started += instance.OnDevTools;
                @DevTools.performed += instance.OnDevTools;
                @DevTools.canceled += instance.OnDevTools;
                @NoClip.started += instance.OnNoClip;
                @NoClip.performed += instance.OnNoClip;
                @NoClip.canceled += instance.OnNoClip;
                @UnlockPowers.started += instance.OnUnlockPowers;
                @UnlockPowers.performed += instance.OnUnlockPowers;
                @UnlockPowers.canceled += instance.OnUnlockPowers;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @FastSlide.started += instance.OnFastSlide;
                @FastSlide.performed += instance.OnFastSlide;
                @FastSlide.canceled += instance.OnFastSlide;
                @Crawl.started += instance.OnCrawl;
                @Crawl.performed += instance.OnCrawl;
                @Crawl.canceled += instance.OnCrawl;
            }

            private void UnregisterCallbacks(IPlayerControlsActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @Throw.started -= instance.OnThrow;
                @Throw.performed -= instance.OnThrow;
                @Throw.canceled -= instance.OnThrow;
                @FastFall.started -= instance.OnFastFall;
                @FastFall.performed -= instance.OnFastFall;
                @FastFall.canceled -= instance.OnFastFall;
                @RecallLast.started -= instance.OnRecallLast;
                @RecallLast.performed -= instance.OnRecallLast;
                @RecallLast.canceled -= instance.OnRecallLast;
                @RecallAll.started -= instance.OnRecallAll;
                @RecallAll.performed -= instance.OnRecallAll;
                @RecallAll.canceled -= instance.OnRecallAll;
                @QuickBounce.started -= instance.OnQuickBounce;
                @QuickBounce.performed -= instance.OnQuickBounce;
                @QuickBounce.canceled -= instance.OnQuickBounce;
                @Interact.started -= instance.OnInteract;
                @Interact.performed -= instance.OnInteract;
                @Interact.canceled -= instance.OnInteract;
                @Pause.started -= instance.OnPause;
                @Pause.performed -= instance.OnPause;
                @Pause.canceled -= instance.OnPause;
                @DevTools.started -= instance.OnDevTools;
                @DevTools.performed -= instance.OnDevTools;
                @DevTools.canceled -= instance.OnDevTools;
                @NoClip.started -= instance.OnNoClip;
                @NoClip.performed -= instance.OnNoClip;
                @NoClip.canceled -= instance.OnNoClip;
                @UnlockPowers.started -= instance.OnUnlockPowers;
                @UnlockPowers.performed -= instance.OnUnlockPowers;
                @UnlockPowers.canceled -= instance.OnUnlockPowers;
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @FastSlide.started -= instance.OnFastSlide;
                @FastSlide.performed -= instance.OnFastSlide;
                @FastSlide.canceled -= instance.OnFastSlide;
                @Crawl.started -= instance.OnCrawl;
                @Crawl.performed -= instance.OnCrawl;
                @Crawl.canceled -= instance.OnCrawl;
            }

            public void RemoveCallbacks(IPlayerControlsActions instance)
            {
                if (m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerControlsActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerControlsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_Start;
        public struct UIActions
        {
            private @PlayerInputActions m_Wrapper;
            public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Start => m_Wrapper.m_UI_Start;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @Start.started -= instance.OnStart;
                @Start.performed -= instance.OnStart;
                @Start.canceled -= instance.OnStart;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);
        public interface IPlayerControlsActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnThrow(InputAction.CallbackContext context);
            void OnFastFall(InputAction.CallbackContext context);
            void OnRecallLast(InputAction.CallbackContext context);
            void OnRecallAll(InputAction.CallbackContext context);
            void OnQuickBounce(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
            void OnDevTools(InputAction.CallbackContext context);
            void OnNoClip(InputAction.CallbackContext context);
            void OnUnlockPowers(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnFastSlide(InputAction.CallbackContext context);
            void OnCrawl(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnStart(InputAction.CallbackContext context);
        }
    }
}
